name: CIgp  # CI with Gradle Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2   # Check out your code

      # Setup Java JDK 11
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Use Temurin distribution (AdoptOpenJDK)
          java-version: 11          # Specific Java 11 version

      # Setup Gradle 7.0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.0

      # Execute Gradle build (customize this step)
      - name: Build and Test with Gradle
        run: ./build_test.sh

      # Upload artifacts (customize file patterns if needed)
      - uses: actions/upload-artifact@v3
        with:
          name: server-artifact
          path: server/build/libs/*.jar
