name: CIgp

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # --- Gradle Configuration ---
      - name: Setup Gradle 6.7
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7 

      # --- Building and Testing ---
      - name: Build and Test with Gradle
        run: ./gradlew build test

      # --- Uploading Artifacts ---
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-jar  # More descriptive name
          path: server/build/libs/*.jar
